### ISSUE TITLE
Add compiler json output option

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta#1206]
Enable to compiler to produce a structured output format for consumption by automated tooling

Add specific support to distinguish User Defined Exceptions

**Comment by sanderr** [comment]
Is there any spec for what this should look like? If not, would something like this be acceptable?
```json
{
	"errors": {
		"plugin_exceptions": [
			{
				"message": "the error message",
				"location": "the location"
			}
		],
		"parse_errors": [],
		"runtime_errors": []
	}
}
```
Currently this will never be populated by more than one error, but if we want to go more towards automated tooling, it might be interesting to add this flexibility towards the future.
Should anything other than errors be present in this initial stage?

**Comment by sanderr** [comment]
I just had another look at #49 and it seems like it's more complicated than I presented above. Should the top level be instances, where each instance could have possible errors?

**Comment by wouterdb** [comment]
Could you elaborate on that?

**Comment by wouterdb** [comment]
For location, it might be good to stay in line with the language server protocol specification (https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/) 

This gives us a clear definition. (Or make our own similarly well defined format)

**Comment by sanderr** [comment]
I agree, following a well-established specification like the LSP seems like the best approach.

Elaboration: I should have phrased it more like a question because I'm actually not sure what is expected here. In #49 you specify "each service instance gets a `warnings` attribute that reports all warnings for this service". Does this mean that the compiler should group errors by instance? Or is the idea to convert this later on the LSM side? If so, is the example structure I gave above sufficient?
Side note: do you think it's a good idea to group by error type as I did above, or would you prefer a flat list where each error object has a "type" field?

**Comment by wouterdb** [comment]
1. flat list with types is probably easier to handle
2. the per instance is for LSM, as the core has no notion of service instance
3. there must be a clear way/convention to add additional fields, on a per type basis.

**Comment by sanderr** [comment]
3. You're referring to the implementation here, not the json structure itself, right?

**Comment by wouterdb** [comment]
3. the idea is that any exception can cause additional fields to be in the json.
