### ISSUE TITLE
pytest: path to pg_ctl

### ISSUE THREAD

**Issue by kazaamjt** [inmanta/inmanta#1381]
Currently the path to pg_ctl is hardcoded in pytest.ini:

https://github.com/inmanta/inmanta/blob/e725b7375b8c2e1de45ca8c2b80b9731843ce04a/pytest.ini#L2

However, on Debian for example, the path to pg_ctl is:
_/usr/lib/postgresql/11/bin/pg_ctl_

Instead a more platform independent approach should be implemented.

**Comment by sanderr** [comment]
The initial cause for the creation of this issue is no longer present ([a4543ed](https://github.com/inmanta/inmanta/commit/a4543ed64d7da03aa9a8e7b714dc5f4ae71276e2)). @bartv is your comment regarding the documentation still relevant? If so, what exactly should be documented? The fact that you need either `pg_ctl` or `pg_config` in your PATH?

**Comment by kazaamjt** [comment]
I don't think it needs to be added to the documentation. Installing PostgreSQL using any package should make pg_ctl available on the path.

**Comment by bartv** [comment]
I think we can safely close this one
