### ISSUE TITLE
No location reported on missing type in index

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#1652]
```
entity Test_A:
    string name
end

index TestA(name)
```

This reports that TestA is not found, however it does not report a location. In a relation for example the location is reported.

**Comment by sanderr** [comment]
I believe this one might require a refactor throughout the compiler.

@wouterdb, currently the `get_type()` methode of `Namespace` accepts a `str`. It has no knowledge of location so it can't attach this information to the `TypeNotFoundException` it raises. I see two possible solutions:
- pass on `LocatableString` instead of `str` to `get_type()`
- at every call of `get_type()` (and probably a lot of similar methods) catch the error, attach the location and raise it again.

The first seems the cleanest since it makes abstraction of the location attachment.
Neither solution is really satisfactory though. Since `LocatableString` does not inherit from `str` it can't just be passed to methods that do expect `str` values. This means a lot of explicit casting is required. For example `DefineIndex` and all other callers need to store the `LocatableString` value instead of the current `str` value. For methods where the `str` value is required it needs to be casted. The same in the implementation of `get_type()` and similar. The exceptions should be passed the `LocatableString` while most other operations should act on the `str`.

It's a shame we can't just extend `str`, that would make all this so much easier. Alternatively we could just mimic `str` behavior, but that wouldn't allow for typing a `LocatableString` value as `str`.

Overall I'd opt for the first suggestion: change the parameter type of `get_type()` and update all callers to store the `LocatableString` instead of the `str` so it can be passed.

What do you think?
