### ISSUE TITLE
Nullable attributes should not be optional

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#1775]

**Comment by sanderr** [comment]
This issue is about the semantics for attributes declared as `base_type?`.
- current semantics: can be set to a value of `base_type`, to `null` or can remain unset.
- desired semantics: must be set to either value of `base_type` or to `null`.

approach:
- [ ] add deprecation warning (`FutureWarning`?) when nullable attribute does not get a value assigned
- [ ] create a new issue for actually removing support

**Comment by sanderr** [comment]
`OptionVariable` should not be purged as suggested above as it is also used to represent `[0:1]` relational attributes. #1888 contains more information about the actual required steps to remove support.
