### ISSUE TITLE
Compile queue can fill up very quickly

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#2137]
When a model with many facts is deployed and then "cleaned" the onboarding causes many facts to arrive in a small timeslot. This causes the compiler queue to fill up with many compiles that actually will all do the same.

See screenshot

![2020-05-19_10-34](https://user-images.githubusercontent.com/10819/82308786-8efef480-99c2-11ea-8862-e64547bce0f6.png)

**Comment by wouterdb** [comment]
The compile server should collapse identical compiles

**Comment by sanderr** [comment]
How are identical compiles defined? Same `environment`, `do_export`, `force_update`, `metadata` and `environment_variables`?

**Comment by wouterdb** [comment]
things that are certainly important to equality:
- environment
- do_export
- environment_variables

force_update, in fact, can be merged through application of `or` operator)

The metadata I don't know for sure, it might contain data that makes merging impossible. 
It also isn't used by the compiler (it is passed as-is back to the server).
For lsm validation, I think it contains unique metadata, but validation will/should at this point never be merged (it would be incorrect to merge, environment_variables are always different). 

It would be good it investigate this in detail.  For the common scenarios that we want to merge does it merge if we also compare meta-data? (Is there some unique medta-data)

Common scenarios

- facts coming in, in batches
- user mashing the recompile button
- export storm on LSM due to many services going to a failure state at the same time  (this one may be too complex to handle in the generic case and can be deferred if that is the case)


now I think of it sending out notification also has to be done correctly for merged compiles.

**Comment by sanderr** [comment]
A couple of questions about entry-points:
- For displaying the compile queue in the dashboard, `CompilerService.get_compile_queue()` is used?
- For adding compile requests to the queue `CompilerService.request_recompile()` is an entrypoint, but they might just as well be inserted directly into the database?

@wouterdb , you mention "Additional concern is that the report for the one compile should be available under the ID of all those compiles." Why is this the case? I assume you're talking about the `remote_id`? How/when is this generated? Would it be possible to circumvent creation of a new id when a new compile request merges with an existing one?

**Comment by wouterdb** [comment]
This service should encapsulate the underlying database, so CompilerService.get_compile_queue() and CompilerService.request_recompile() are two entry points. 

the remote_id is set by the remote side (hence the name), it allows idempotence when requesting a compile (by having the ability to set the remote_id)

For compile reports, lsm e.g. uses remote_id to link a validation event log to a compile. 
However, the request_compile also return the compile_id, so if compaction is done in request_compile, the correct compile_id can be returned. If compaction is done later, the consistency problem exists, because two different compile_id's are return for the same compile.
