### ISSUE TITLE
Inconsistent environment id

### ISSUE THREAD

**Issue by automate-solutions** [inmanta/inmanta#444]
When deploying with the CLI
`inmanta -vvv deploy`
I see in the debug logs that this environment ID is present for the agents:
```
DEBUG    New session for agent iaas_openstack on inmanta-dev
DEBUG    New session for agent internal on inmanta-dev
DEBUG    set session 2a63fa02-5d8e-11e7-9fed-000c29543e51 as primary for agent iaas_openstack in env 29f94ab1-0962-46f9-8157-71f69b450101
DEBUG    set session 2a63fa02-5d8e-11e7-9fed-000c29543e51 as primary for agent internal in env 29f94ab1-0962-46f9-8157-71f69b450101
DEBUG    Started new agent with PID 5370
INFO     ['iaas_openstack', 'internal'] matches agents managed by server, ensuring it is started.
std::AgentConfig[internal,agentname=iaas_openstack],v=1498825082 - deployed
openstack::VirtualMachine[iaas_openstack,name=testhost],v=1498825082 - deployed
openstack::HostPort[iaas_openstack,name=testhost_eth0],v=1498825082 - deployed
[3 / 3]
Deploy ready
DEBUG    expiring session 2a63fa02-5d8e-11e7-9fed-000c29543e51
```
The `.inmanta` contains:
```
[root@inmanta-dev openstack-template]# cat .inmanta 

[config]
heartbeat-interval = 60
fact-expire = 1800
environment=e3cb350c-52b7-461c-90a3-cbc5e04757c5


[compiler_rest_transport]
host = localhost
port = 8888

[cmdline_rest_transport]
host=localhost
port=8888
```
This environment ID is also not present here:
```
[root@inmanta-dev openstack-template]# inmanta-cli environment list
+-------------------------+--------------------------------------+-----------------------------+--------------------------------------+
|      Project name       |              Project ID              |         Environment         |            Environment ID            |
+=========================+======================================+=============================+======================================+
| openstack-dev           | 4ad5dad5-4ece-4ca7-9f62-35b66242f7ba | openstack-dev-env           | 177e8866-2a4e-47b0-8230-fff7499a09b6 |
| openstack-template-test | e2c0750d-e2e5-4219-bc4a-afec555925b1 | openstack-template-test-env | e3cb350c-52b7-461c-90a3-cbc5e04757c5 |
+-------------------------+--------------------------------------+-----------------------------+--------------------------------------+
```
And, of course, if I try to use the `env_id` variable in a template, like in:
```
[config]
heartbeat-interval = 60
fact-expire = 60
state-dir=/var/lib/inmanta
environment={{ env_id }}
agent-names=\$node-name
```
It pushes the wrong environment ID on the created instance:
```
[config]
heartbeat-interval = 60
fact-expire = 60
state-dir=/var/lib/inmanta
environment=29f94ab1-0962-46f9-8157-71f69b450101
```

If I deploy it with the GUI, everything is fine:
```
[config]
heartbeat-interval = 60
fact-expire = 60
state-dir=/var/lib/inmanta
environment=e3cb350c-52b7-461c-90a3-cbc5e04757c5
```
I can event see the agent in the dashboard:
<img width="1011" alt="screen shot 2017-06-30 at 14 31 36" src="https://user-images.githubusercontent.com/28261191/27735708-4bb99eec-5da1-11e7-81b5-9495fba23800.png">

**Comment by bartv** [comment]
1) The depoy command is completely standalone. It creates a project and environment specific on the embeded server of the deploy command. This uuid is only shown in log files. Normally it should persist over deploy invocations as long as you keep the data dir in the project directory. Due to bug #443 no data is persisted at all and every deploy invocation another environment with a new uuid is created.

The deploy command wil NOT work with a server that is running somewhere.

2) The .inmanta file contains a uuid that you can use to export to a server that is running somewhere. If you do inmanta export it will use the settings in .inmanta (environment id and the connection settings). For example:
```
[config]
environment=044eccd7-7488-4c27-8735-e5f85d433630

[compiler_rest_transport]
host = dev01.inmanta.com
port = 8080
```
This uuid has to match with the id on the server. If the environment id does not exist on the server, you will get an error.

The compiler / export command will use the id in .inmanta or the config file passed with -c.

**Comment by bartv** [comment]
This is not really an issue, can I close it? Or is there something we can do to improve the experience here?

(You may also use the #inmanta irc channel on freenode for questions.)
